/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c DemoAdaptor2 -a demoadaptor2.h:demoadaptor2.cpp .\cn.kylinos.dbusdemoiface2.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef DEMOADAPTOR2_H
#define DEMOADAPTOR2_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface cn.kylinos.dbus.demo2
 */
class DemoAdaptor2: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "cn.kylinos.dbus.demo2")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"cn.kylinos.dbus.demo2\">\n"
"    <method name=\"increase\"/>\n"
"    <method name=\"decrease\"/>\n"
"    <method name=\"reset\"/>\n"
"  </interface>\n"
        "")
public:
    DemoAdaptor2(QObject *parent);
    virtual ~DemoAdaptor2();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void decrease();
    void increase();
    void reset();
Q_SIGNALS: // SIGNALS
};

#endif
