/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c DemoAdaptor1 -a demoadaptor1.h:demoadaptor1.cpp .\cn.kylinos.dbusdemoiface.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "demoadaptor1.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DemoAdaptor1
 */

DemoAdaptor1::DemoAdaptor1(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DemoAdaptor1::~DemoAdaptor1()
{
    // destructor
}

void DemoAdaptor1::decrease()
{
    // handle method call cn.kylinos.dbus.demo1.decrease
    QMetaObject::invokeMethod(parent(), "decrease");
}

void DemoAdaptor1::get()
{
    // handle method call cn.kylinos.dbus.demo1.get
    QMetaObject::invokeMethod(parent(), "get");
}

void DemoAdaptor1::increase()
{
    // handle method call cn.kylinos.dbus.demo1.increase
    QMetaObject::invokeMethod(parent(), "increase");
}

void DemoAdaptor1::reset()
{
    // handle method call cn.kylinos.dbus.demo1.reset
    QMetaObject::invokeMethod(parent(), "reset");
}

