/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c DbusDemoIface1 -p demoif1.h:demoif1.cpp .\cn.kylinos.dbusdemoiface.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "demoif1.h"

/*
 * Implementation of interface class DbusDemoIface1
 */

DbusDemoIface1::DbusDemoIface1(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

DbusDemoIface1::~DbusDemoIface1()
{
}

