/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c DemoAdaptor2 -a demoadaptor2.h:demoadaptor2.cpp .\cn.kylinos.dbusdemoiface2.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "demoadaptor2.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DemoAdaptor2
 */

DemoAdaptor2::DemoAdaptor2(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DemoAdaptor2::~DemoAdaptor2()
{
    // destructor
}

void DemoAdaptor2::decrease()
{
    // handle method call cn.kylinos.dbus.demo2.decrease
    QMetaObject::invokeMethod(parent(), "decrease");
}

void DemoAdaptor2::increase()
{
    // handle method call cn.kylinos.dbus.demo2.increase
    QMetaObject::invokeMethod(parent(), "increase");
}

void DemoAdaptor2::reset()
{
    // handle method call cn.kylinos.dbus.demo2.reset
    QMetaObject::invokeMethod(parent(), "reset");
}

