/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c DemoAdaptor1 -a demoadaptor1.h:demoadaptor1.cpp .\cn.kylinos.dbusdemoiface.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef DEMOADAPTOR1_H
#define DEMOADAPTOR1_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface cn.kylinos.dbus.demo1
 */
class DemoAdaptor1: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "cn.kylinos.dbus.demo1")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"cn.kylinos.dbus.demo1\">\n"
"    <method name=\"increase\"/>\n"
"    <method name=\"decrease\"/>\n"
"    <method name=\"get\"/>\n"
"    <method name=\"reset\"/>\n"
"    <signal name=\"valueChanged\"/>\n"
"  </interface>\n"
        "")
public:
    DemoAdaptor1(QObject *parent);
    virtual ~DemoAdaptor1();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void decrease();
    void get();
    void increase();
    void reset();
Q_SIGNALS: // SIGNALS
    void valueChanged();
};

#endif
